# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 7 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nikiforovall
google_analytics: UA-164555539-1
title: N+1 Blog

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: nikiforovall.blog

description: Blog
author:
  name: Oleksii Nikiforov
  email: alexey.nikiforovall@gmail.com
  github: nikiforovAll
  twitter: nikiforovall
  telegram: nikiforovallblog
  linkedin: nikiforov-oleksii
  bio: Jibber-jabbering about programming and IT.
  email_md5: e86fa0938976c38907a302ecb208f011

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://secure.gravatar.com/avatar/e86fa0938976c38907a302ecb208f011

BASE_PATH: https://nikiforovall.github.io

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-target-blank

# Site structure
about_page_path: "about.html"
